### ISSUE TITLE
The .csv.gz files for unpaired and paired sequences on the web portal are not opening

### ISSUE THREAD

**Issue by AleksZakirov** [brennanaba/PLAbDab#1]
Hi! Thanks very much for the great resource!

Unfortunately it seems like the files under the links for paired and unpaired sequences from the web portal are corrupted in some manner. I am using a chrome browser on a mac machine, and when I download the files and try to open them I get the following error message: 
<img width="386" alt="image" src="https://github.com/brennanaba/PLAbDab/assets/45701243/f6cdabbc-98e1-4db1-8e8b-70d3e6e6bed9">

When downloading the whole database "plabdab_data", I found the same files in the folder and those can be unarchived and opened without any issues.

**Comment by brennanaba** [comment]
Hi Aleks,

Thank you for bringing this to our attention. We appreciate your interest in our resource and we apologize for any inconvenience caused by the issue.

To clarify, the original files on our server aren't corrupt, but it appears there could be an issue with the files getting corrupted during download. This is often due to some browser settings which automatically try to extract compressed files upon download, potentially leading to issues such as the one you're experiencing.

We are currently investigating the issue and seeking a comprehensive solution. In the meantime, there are a couple of workarounds you could try:

1. Disable the automatic extraction feature on your browser. The steps to do this may vary depending on your browser.

2. Download the data directly via Python using the pandas library. Here's a brief code snippet on how to achieve that:

```python
import pandas as pd

url = "https://opig.stats.ox.ac.uk/webapps/plabdab/static/downloads/paired_sequences.csv.gz"
df = pd.read_csv(url, compression='gzip')
```

This should bypass the need for manual extraction and allow you to directly access the data. 

Thank you for your patience and understanding as we work to resolve this issue. If you encounter any other problems, please don't hesitate to let us know.

All the best,

Brennan
